### ISSUE TITLE
Direct interaction with the agents from Java code

### ISSUE THREAD

**Issue by fnmartinez** [janus-project/janusproject#110]
Hi! 

I was wondering if there was a way to interact directly with the agents spawned with Janus from my Java Code. So far the only way I got to do that is to spawn an agent that on Initialization emits a new Event in SARL. But I believe that to be a little extreme and costly. So I was wondering if I could simply get my agent's reference through the UUID.

This is also needed because I have to get data from my agents to plot it in a web interface.

Regards!

**Comment by fnmartinez** [comment]
I've just realized I could send an object that contains all the agents on the Initialize event's parameters. And each agent could set themselves in it, so I could access them as pleased.

But this is a very troublesome way to do it, I believe. It also creates high coupling.

**Comment by gallandarakhneorg** [comment]
This is a large problem. Indeed, according to agent theory, it should be impossible to access to attributes of an agent directly. Indeed, the agent must always have the control on it, and if the agent is migrating on another computer, the access to the attribute becomes impossible.

In your previous agent platform, we have introduced the feature of "probing" the agents in a way the agents are not aware of the probing of there attributes and the platform is managing any other issue.

Unfortunately, this feature is not available in the Janus platform version 2. Indeed, the platform is fully distributed so that the agent may be on a remote computer. The feature of probing is a feature that is currently under discussion.

But for solving you problem before, I may recommend you an implementation approach.
When I need to code an agent that is updating an UI, I define an interface in Java that represents the UI:
```java
public interface AgentUpdateListener {
   void update(UUID id, Object myData1, Object myData2);
}
```

Then, in the UI, I code an implementation that update the UI fields.

In the agent, I assumes that the first argument given to the agent when it is spawn is the AgentUpdateListener instance:
```
agent MyAgent {
    var agentUpdateListener : AgentUpdateListener
    var myAttr1 : Object
    var myAttr2 : Object
    on Initialize {
        this.agentUpdateListener = occurrence.parameters.get(0) as AgentUpdateListener
    }
    def notifyChange {
        this.uiUpdateListener.update(UUID, this.myAttr1, this.myAttr2)
    }
    on Something {
        this.myAttr1 = ...
        notifyChange
    }
}
```

This is a way to implement in SARL the Observer design pattern that is well-known in object-oriented programming.

**Comment by fnmartinez** [comment]
As you stated, it is a problem, albeit an interesting one. As you are saying, according to the theory, I shouldn't be able to access my agents' attributes directly. My solution was along the lines of an observer pattern. The thing that doesn't seems to add up in my case, is that following the lines of an MVC architecture, the agents ought to be a kind of Entity to which I should be able to probe directly on demand. To follow each agent in my system through a kind of map that contains each one values seems like an overkill. 

The probing methodology, although I don't know how it worked in the previous platform, sounds like the right way. At least it would be for my case.

Yours seems to be more suitable in the case of a reactive UI, but hungs a lot implementation stress on the agent side.

**Comment by gallandarakhneorg** [comment]
Probing technology is based on Java reflection. I think this is the more generic and suitable technique (regarding the agent theory and the distributed agent execution) for obtaining attribute value.

Note that your approach may be not compilable is future version of SARL if we decide to change the default vibility of the agent fields (currently: protected). For now, it's ok.

**Comment by fnmartinez** [comment]
Yes, I understand. Thank you very much for the advice. I've made accessor methods to get my agents' state, in the deem hope that future implementations make something along the lines of proxys.

**Comment by gallandarakhneorg** [comment]
The discussion related to the interaction of an Agent with an external Object is [here](https://github.com/sarl/sarl/issues/342)
